default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_crud_books_app_development

test:
  <<: *default
  database: rails_crud_books_app_test

production:
  <<: *default
  database: rails_crud_books_app_production
  username: rails_crud_books_app
  password: <%= ENV['RAILS_CRUD_BOOKS_APP_DATABASE_PASSWORD'] %>
